name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js and cache pnpm packages
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Install pnpm globally
      - run: npm install -g pnpm
      # Debug the installation
      - run: pnpm --version

      # Install project dependencies using pnpm
      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      # Run Nx commands for linting, testing, and building
      - run: npx nx affected -t lint test build
      - run: npx nx affected --parallel 1 -t e2e-ci
