name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      # Install Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v4

      # Run Nx commands for linting, testing, and building
      - run: npx nx affected -t lint test build
      - run: npx nx affected --parallel 1 -t e2e-ci
