name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: master  # Ensure the master branch is checked out

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Cache pnpm modules
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Verify pnpm installation
      - name: Check pnpm version
        run: pnpm --version

      # Ensure the working directory is correct
      - name: Print working directory
        run: pwd

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - uses: nrwl/nx-set-shas@v4

      # Run Nx commands for linting, testing, and building
      - name: Run Nx commands
        run: |
          npx nx affected -t lint test build --verbose
          npx nx affected --parallel 1 -t e2e-ci --verbose
        env:
          NX_BASE: ''
          NX_HEAD: ${{ github.sha }}
